// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/AdminHeader.vue')['default']
    AdminMenuSearch: typeof import('./components/menu/AdminMenuSearch.vue')['default']
    AuthanticatedUserMenu: typeof import('./components/AuthanticatedUserMenu.vue')['default']
    AuthConfirmation: typeof import('./components/AuthConfirmation.vue')['default']
    BusinessCard: typeof import('./components/menu/BusinessCard.vue')['default']
    CarbonAdd: typeof import('~icons/carbon/add')['default']
    CarbonCloudUpload: typeof import('~icons/carbon/cloud-upload')['default']
    CarbonEdit: typeof import('~icons/carbon/edit')['default']
    CarbonFavorite: typeof import('~icons/carbon/favorite')['default']
    CarbonFavoriteFilled: typeof import('~icons/carbon/favorite-filled')['default']
    CarbonHeart: typeof import('~icons/carbon/heart')['default']
    CarbonLike: typeof import('~icons/carbon/like')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonPhone: typeof import('~icons/carbon/phone')['default']
    CarbonSettings: typeof import('~icons/carbon/settings')['default']
    CarbonStudyNext: typeof import('~icons/carbon/study-next')['default']
    CarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    CarbonWifi: typeof import('~icons/carbon/wifi')['default']
    ConfirmModal: typeof import('./components/shared/ConfirmModal.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GlobalModal: typeof import('./components/shared/GlobalModal.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    MenuCategory: typeof import('./components/menu/MenuCategory.vue')['default']
    MenuItem: typeof import('./components/menu/MenuItem.vue')['default']
    MenuSearch: typeof import('./components/menu/MenuSearch.vue')['default']
    README: typeof import('./components/README.md')['default']
    UserMenuDropdown: typeof import('./components/menu/UserMenuDropdown.vue')['default']
  }
}

export { }
